apiVersion: v1
kind: Secret
metadata:
  name: cb-example-auth
type: Opaque
data:
  username: QWRtaW5pc3RyYXRvcg==  # Administrator
  password: cGFzc3dvcmQ=          # password
---
apiVersion: couchbase.com/v2
kind: CouchbaseBucket
metadata:
  name: cars  
spec:
  memoryQuota: 128Mi
---
apiVersion: couchbase.com/v2
kind: CouchbaseCluster
metadata:
  name: cb-example  
spec:
  image: couchbase/server:6.6.0  
  security:
    adminSecret: cb-example-auth
  networking:
    exposeAdminConsole: true
    adminConsoleServices:
    - data
  buckets:
    managed: true
  servers:
  - size: 3  
    name: all_services
    services:
    - data
    - index
    - query
    - search
    - eventing
    - analytics



# apiVersion: couchbase.com/v2
# kind: CouchbaseCluster
# metadata:
#   name: cb-hellomicroservices
# spec:
#   baseImage: couchbase
#   version: 6.5.0-beta2
#   authSecret: cb-hellomicroservices-auth
#   exposeAdminConsole: true
#   adminConsoleServices:
#     - data
#   cluster:
#     dataServiceMemoryQuota: 256
#     indexServiceMemoryQuota: 256
#     searchServiceMemoryQuota: 256
#     eventingServiceMemoryQuota: 256
#     analyticsServiceMemoryQuota: 1024
#     indexStorageSetting: plasma
#     autoFailoverTimeout: 30
#     autoFailoverMaxCount: 3
#     autoFailoverOnDataDiskIssues: true
#     autoFailoverOnDataDiskIssuesTimePeriod: 30
#     autoFailoverServerGroup: false
#   buckets:
#     - name: cars
#       type: couchbase
#       memoryQuota: 256
#       replicas: 0
#       ioPriority: high
#       evictionPolicy: fullEviction
#       conflictResolution: seqno
#       enableFlush: false
#       enableIndexReplica: false
#   servers:
#     - size: 1
#       name: all_services
#       services:
#         - data
#         - index
#         - query
# ---
# apiVersion: v1
# kind: Secret
# metadata:
#   name: cb-hellomicroservices-auth
# type: Opaque
# data:
#   username: QWRtaW5pc3RyYXRvcg== # Administrator
#   password: cGFzc3dvcmQ= # password