---
apiVersion: v1
kind: Secret
metadata:
  name: cb-example-auth
type: Opaque
data:
  username: QWRtaW5pc3RyYXRvcg==  # Administrator
  password: cGFzc3dvcmQ=          # password
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: couchbase
  name: couchbase
spec:
  replicas: 1
  selector:
    matchLabels:
      app: couchbase
  strategy: {}
  template:
    metadata:
      labels:
        app: couchbase
    spec:
      containers:
      - image: couchbase/server-sandbox:6.6.0
        name: couchbase
        ports:
        - containerPort: 8091
        - containerPort: 8092
        - containerPort: 8093
        - containerPort: 8094
        - containerPort: 11210
        resources: {}
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: couchbase
  name: couchbase
spec:
  ports:
  - name: 8091-8091
    port: 8091
    protocol: TCP
    targetPort: 8091
  - name: 8092-8092
    port: 8092
    protocol: TCP
    targetPort: 8092
  - name: 8093-8093
    port: 8093
    protocol: TCP
    targetPort: 8093
  - name: 8094-8094
    port: 8094
    protocol: TCP
    targetPort: 8094
  - name: 11210-11210
    port: 11210
    protocol: TCP
    targetPort: 11210
  selector:
    app: couchbase
  type: ClusterIP
---
apiVersion: apps/v1 
kind: Deployment
metadata:
  name: cardata
spec:
  selector:
    matchLabels:
      app: cardata
  replicas: 1 # tells deployment to run # pods matching the template
  template: # create pods using pod definition in this template
    metadata:
      labels:
        app: cardata
    spec:
      containers:
      - name: go-web-app
        image: qpetraroia.azurecr.io/go-web-app
        imagePullPolicy: Always
        ports:
        - containerPort: 12345
          name: server
        env:
        - name: Couchbase__Username
          valueFrom:
            secretKeyRef:
              name: cb-hellomicroservices-auth
              key: username
        - name: Couchbase__Password
          valueFrom:
            secretKeyRef:
              name: cb-hellomicroservices-auth
              key: password
        - name: DB_HOST
          value: cb-example
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 250m
            memory: 256Mi
---
apiVersion: v1
kind: Service
metadata:
  name: cardata
spec:
  ports:
  - port: 80
    targetPort: 12345
    protocol: TCP
  selector:
    app: cardata
  type: LoadBalancer

